package com.dmims.dmims.model

class GetAdminData {
    var ID:String = "-"
    var ADMIN_NAME:String = "-"
    var ADMIN_MOBILE_NO:String = "-"
    var USER_ROLE:String = "-"
    var INSTITUTE_NAME:String = "-"
    var EMAIL:String = "-"
    var DESIGNATION:String = "-"
    var COURSE_ID:String = "-"
    var FNAME:String = "-"
    var MNAME:String = "-"
    var LNAME:String = "-"
    var FID:String = "-"
    var INST_NAME:String = "-"
    var FMOB:String = "-"
    var FEMAIL:String = "-"
    var DOB:String = "-"
    var DOJ:String = "-"
    var GEN:String = "-"
    var PUNCHID:String = "-"
    var DEPNAM01:String = "-"
    var COU_NAM01:String = "-"
    var DEPNAM02:String = "-"
    var COU_NAM02:String = "-"
    var ROLL:String = "-"
    var DEPNAM03:String = "-"
    var COU_NAM03:String = "-"
    var DEPNAM04:String = "-"
    var COU_NAM04:String = "-"
    var DESIG:String = "-"
    var UFMID:String = "-"
    var OTP:String = "-"

}